config/routes.rb
AssetManager::Engine.routes.draw do
  resources :assets, path: 'managed_assets' do
    collection do
      get 'preview'
      get 'select'
      get 'multiple_select'
      post 'quick_upload'
    end
    member do
      get 'show/:context', to: 'asset_instances#show', as: :render
      get 'admin_show/:context', to: 'asset_instances#admin_show', as: :admin_render
      get 'download/:context', to: 'asset_instances#show', as: :download, download: true
      get 'admin_download/:context', to: 'asset_instances#admin_show', as: :admin_download, download: true
    end
  end
  resources :asset_categories

  get 'index/index'
  root to: 'assets#index'
end

app/models/asset_manager/asset_association.rb
module AssetManager
  class AssetAssociation < ActiveRecord::Base
    # attr_accessible :context, :owner_id, :owner_type, :asset_id, :position

    belongs_to :asset, class_name: 'AssetManager::Asset'
    belongs_to :owner, polymorphic: true

    validates :asset_id, presence: true
    # validates :owner_id, presence: true
    validates :owner_type, presence: true
    validates :context, presence: true

    default_scope { order(:position) }
  end
end

app/models/asset_manager/asset_private_instance.rb
module AssetManager
  class AssetPrivateInstance < AssetManager::AssetInstance
    belongs_to :asset, class_name: 'AssetManager::Asset', foreign_key: 'asset_id', inverse_of: :asset_private_instances
    mount_uploader :file, AssetPrivateUploader
  end
end

app/controllers/asset_manager/application_controller.rb
module AssetManager
  class ApplicationController < ActionController::Base
  end
end

app/controllers/asset_manager/asset_categories_controller.rb
require_dependency 'asset_manager/application_controller'

module AssetManager
  class AssetCategoriesController < ApplicationController
    def index
      @q = AssetManager::AssetCategory.ransack(params[:q])
      @asset_categories = @q.result.send(Kaminari.config.page_method_name, params[Kaminari.config.param_name]).per(50).order('id DESC')
      @total_records = @q.result.count
    end

    def show
      @asset_category = AssetCategory.find(params[:id])
    end

    def new
      @asset_category = AssetCategory.new
      @asset_category = build_translations(@asset_category)
    end

    def edit
      @asset_category = AssetCategory.find(params[:id])
      @asset_category = build_translations(@asset_category)
    end

    def create
      @asset_category = AssetCategory.new(resource_params)
      if @asset_category.save
        redirect_to edit_asset_category_url(@asset_category), flash: { success: t('asset_manager.asset_categories.controller.asset_category_successfully_create') }
      else
        render action: 'new'
      end
    end

    def update
      @asset_category = AssetCategory.find(params[:id])
      if @asset_category.update_attributes(resource_params)
        redirect_to edit_asset_category_url(@asset_category), flash: { success: t('asset_manager.asset_categories.controller.asset_category_successfully_update') }
      else
        render action: 'edit'
      end
    end

    def destroy
      @asset_category = AssetCategory.find(params[:id])
      @asset_category.destroy
      redirect_to asset_categories_url
    end

    private

    def build_translations(asset_category)
      asset_category.translations_for_locales(I18n.available_locales)
      asset_category
    end

    def resource_params
      params.require(:asset_category).permit(:id, translations_attributes: [:id, :title, :locale])
    end
  end
end

app/controllers/asset_manager/asset_instances_controller.rb
require_dependency 'asset_manager/application_controller'

module AssetManager
  class AssetInstancesController < ApplicationController
    def show
      asset_instance = AssetManager::AssetPrivateInstance.find_by_asset_id_and_instance_context(params[:id], params[:context])
      path = (params[:version].present? ? asset_instance.file.url(params[:version]) : asset_instance.file.url)
      disposition = params[:download] ? :attachment : :inline
      send_file path, disposition: disposition
    end

    alias_method :admin_show, :show

    private

    def store_location
      if request.fullpath != '/users/sign_in' && request.fullpath != '/users/sign_up' && !request.xhr? # don't store ajax calls
        Thread.current[:previous_url] = request.fullpath
      end
    end
  end
end

app/controllers/asset_manager/assets_controller.rb
require_dependency 'asset_manager/application_controller'

module AssetManager
  class AssetsController < ApplicationController
    before_filter :load_public, only: [:index, :new]

    def index
      @q = AssetManager::Asset.search(params[:q])
      @assets = @q.result.send(Kaminari.config.page_method_name, params[Kaminari.config.param_name]).per(50).order('id DESC')
      @total_records = @q.result.count
    end

    def show
      @asset = Asset.find(params[:id])
    end

    def new
      @asset = Asset.new(public: @public)
      @asset = build_translations(@asset)
      @asset = build_asset_instances(@asset)
    end

    def edit
      @asset = Asset.find(params[:id])
      @asset = build_translations(@asset)
      @asset = build_asset_instances(@asset)
    end

    def create
      @asset = Asset.new(resource_params)
      if @asset.save
        redirect_to edit_asset_url(@asset), flash: { success: t('asset_manager.assets.controller.asset_successfully_create') }
      else
        @asset = build_translations(@asset)
        @asset = build_asset_instances(@asset)
        render action: 'new'
      end
    end

    def update
      @asset = Asset.find(params[:id])
      if @asset.update_attributes(resource_params)
        redirect_to edit_asset_url(@asset), flash: { success: t('asset_manager.assets.controller.asset_successfully_update') }
      else
        @asset = build_translations(@asset)
        @asset = build_asset_instances(@asset)
        render action: 'edit'
      end
    end

    def destroy
      @asset = Asset.find(params[:id])
      @asset.destroy
      redirect_to assets_url
    end

    def preview
      @assets = Asset.find_ordered(params[:ids])
      render partial: '/admin/asset_manager/assets/assets', locals: { collection: @assets }
    end

    def select
      @owner = params[:owner]
      @id = params[:id]
      @field = params[:field]
      @save = params[:save]
      @locale = params[:locale]
      @field_name = params[:field_name]

      owner_class = @owner.constantize
      fail ActiveRecord::RecordNotFound.new('Invalid Field') unless owner_class.am_has_field?(@field)

      @multiple = owner_class.am_multiple_field?(@field.to_sym)
      @max = owner_class.am_field_option(@field, :max)
      @type = owner_class.am_field_option(@field, :type)
      @accepted = owner_class.am_field_option(@field, :accepted)

      # Recupero gli asset della risorsa, tramite ids passati come parametro o quelli associati direttamente ad essa
      ids = params[:ids]
      if ids
        @resource_assets = ((ids.length == 1 && ids[0] == 'no') ? [] : Asset.find_ordered(ids))
      else
        @resource_assets = (@id ? Array(owner_class.find(@id).send(@field)) : [])
      end
      ids = @resource_assets.map(&:id)
      # Search
      params[:search][:asset_category_id_in].reject!(&:blank?) rescue nil
      params[:search][:file_type_in].reject!(&:blank?) rescue nil
      @q = AssetManager::Asset.search(params[:q])
      @assets = @q.result
      @assets = @assets.not_ids(ids).public(@type).accepted(@accepted).send(Kaminari.config.page_method_name, params[Kaminari.config.param_name]).per(36).order(AssetManager::Asset.table_name + '.id DESC')
      @assets = @assets.tagged_with(params[:tags], any: true) unless params[:tags].nil?

      render layout: 'asset_manager/simple'
    end

    def quick_upload
      tilte_by_filename = File.basename(params[:asset]["asset_#{params[:asset][:public] == 'true' ? 'public' : 'private'}_instances_attributes".to_sym]['0'][:file].original_filename, '.*').titleize
      params[:asset][:translations_attributes]['0'][:title] = tilte_by_filename
      @asset = Asset.create(resource_params)
    end

    private

    def load_public
      @public = params[:public] == 'false' ? false : true
    end

    def build_asset_instances(asset)
      if asset.asset_instances.empty?
        asset.asset_instances.build(instance_context: AssetManager::AssetInstance.instance_context_all)
      end
      asset
    end

    def build_translations(asset)
      asset.translations_for_locales(I18n.available_locales)
      asset
    end

    def resource_params
      params.require(:asset).permit(:id, :public, :asset_category_id, :tag_list, :file_type,
                                    translations_attributes: [:id, :title, :description, :locale],
                                    asset_public_instances_attributes: [:id, :instance_context, :file, :_destroy],
                                    asset_private_instances_attributes: [:id, :instance_context, :file, :_destroy])
    end
  end
end

app/controllers/asset_manager/index_controller.rb
require_dependency 'asset_manager/application_controller'

module AssetManager
  class IndexController < ApplicationController
    def index
    end
  end
end

app/helpers/asset_manager/application_helper.rb
module AssetManager
  module ApplicationHelper
    def am_title(header, sub_header = nil)
      safe_header = h(header.to_s.truncate(100, separator: ' '))
      content_for(:title) { safe_header }
      safe_header = content_tag(:h1, raw(safe_header))
    end
  end
end

app/helpers/asset_manager/asset_instances_helper.rb
module AssetManager
  module AssetInstancesHelper
    include AssetManager::Deprecated::AssetInstancesHelper

    def am_asset_instance_image(resource, options = {})
      options.assert_valid_keys(:version, :linked, :link_options, :image_options)
      options.reverse_merge!(linked: false, link_options: {}, image_options: {})
      img_src = am_asset_instance_url(resource, version: options[:version])
      img_options = options[:image_options].merge(alt: resource.asset.alt)
      link_href = am_asset_instance_url(resource, version: options[:link_options][:version])
      link_options = options[:link_options].except(:version).merge(title: resource.asset.alt)
      link_to_if options[:linked], image_tag(img_src, img_options), link_href, link_options
    end

    def am_asset_instance_url(resource, options = {})
      options.assert_valid_keys(:version, :download, :force_frontend)
      options.reverse_merge!(version: nil, download: false, force_frontend: false)
      if resource.asset.public
        unless options[:version].nil?
          resource.file.url(options[:version])
        else
          resource.file.url
        end
      else
        if options[:force_frontend] || !in_admin_controller?
          if options[:download]
            asset_manager.download_asset_path(resource.asset, context: resource.instance_context)
          else
            asset_manager.render_asset_path(resource.asset, context: resource.instance_context, version: options[:version])
          end
        else
          if options[:download]
            asset_manager.admin_download_asset_path(resource.asset, context: resource.instance_context)
          else
            asset_manager.admin_render_asset_path(resource.asset, context: resource.instance_context, version: options[:version])
          end
        end
      end
    end

    def am_display_instance_context(resource)
      if resource.is_all?
        display_instance_context_all
      else
        resource.instance_context
      end
    end

    private

    def display_instance_context_all
      raw('&#8659')
    end

    def in_admin_controller?
      controller.class.name =~ /(AssetManager|Admin)::/
    end
  end
end

app/helpers/asset_manager/assets_helper.rb
module AssetManager
  module AssetsHelper
    include AssetManager::Deprecated::AssetsHelper

    def am_render(resource, field, options = {})
      send("am_render_#{resource.class.am_field_option(field, :mode)}", resource.send(field), options)
    end

    def am_render_image(asset, options = {})
      unless asset.nil?
        ais = asset.asset_instances rescue nil
        if ais && ais.count == 1
          am_asset_instance_image(ais.first, options)
        end
      end
    end

    def am_render_images(assets, options = {})
      unless assets.empty?
        result = content_tag(:ul) do
          items = []
          assets.each do |asset|
            items.push(
              content_tag(:li) { am_render_image(asset, options) }
            )
          end
          safe_join items, ''
        end
        raw(result)
      end
    end

    def am_render_file(asset, options = {})
      unless asset.nil?
        options.assert_valid_keys(:ico_size)
        render(partial: 'asset_manager/assets/asset_group_by_instance_context', locals: { resource: asset, ico_size: options[:ico_size] })
      end
    end

    def am_render_files(assets, options = {})
      unless assets.empty?
        options.assert_valid_keys(:ico_size, :categorized)
        options.reverse_merge!(categorized: false)
        (options[:categorized] ?
          am_categorized_assets_group(assets, ico_size: options[:ico_size]) :
          am_assets_group(assets, ico_size: options[:ico_size])
        )
      end
    end

    # Others
    def am_select_link(resource, field, options = {})
      options.assert_valid_keys(:save, :field_name)
      options.reverse_merge!(save: false)
      args = { owner: resource.class.name, id: resource.id, field: field, save: options[:save], field_name: options[:field_name]}
      args[:locale] = resource.locale if resource.respond_to? :locale
      href = asset_manager.select_assets_path(args)
      title = "Asset Manager - #{resource.class.name} - #{field}"
      content_tag(:a, href: href, class: 'asset_manager_iframe', title: title, data: { href: href }) {
        t('select', scope: [resource.class.i18n_scope, resource.class.name.demodulize.tableize, :show], default: 'Select')
      }
    end

    def am_ico_path(type, options = {})
      options.assert_valid_keys(:size)
      options.delete_if { |k, v| v.nil? }.reverse_merge!(size: 16)
      size = options[:size]
      file_name = type.to_s + '.png'
      file_path = ['asset_manager', 'file_icons', (size.to_s + 'x' + size.to_s), file_name].join('/')
      if Rails.application.config.assets.compile
        file = Rails.application.assets.find_asset(file_path)
      else
        file = assets_manifest.assets[file_path]
      end
      unless file.present?
        file_path.gsub!(file_name, 'default.png')
      end
      image_path(file_path)
    end

    def am_clippy(text, options = {})
      options.assert_valid_keys(:bg_color)
      options.reverse_merge!(bg_color: '#FFFFFF')
      html = <<-EOF
        <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
                width="110"
                height="14"
                id="clippy" >
        <param name="movie" value="/assets/clippy.swf"/>
        <param name="allowScriptAccess" value="always" />
        <param name="quality" value="high" />
        <param name="scale" value="noscale" />
        <param NAME="FlashVars" value="text=#{text}">
        <param name="bgcolor" value="#{options[:bg_color]}">
        <embed src="/assets/clippy.swf"
               width="110"
               height="14"
               name="clippy"
               quality="high"
               allowScriptAccess="always"
               type="application/x-shockwave-flash"
               pluginspage="http://www.macromedia.com/go/getflashplayer"
               FlashVars="text=#{text}"
               bgcolor="#{options[:bg_color]}"
        />
        </object>
      EOF
    end

    def am_asset_url(resource, options = {})
      ais = resource.asset_instances rescue nil
      if ais && ais.count == 1
        am_asset_instance_url(ais.first, options)
      end
    end

    private

    def categories_assets(assets)
      items = {}
      assets.each do |asset|
        asset_category = asset.asset_category_id
        items[asset_category] = [] unless items.include?(asset_category)
        items[asset_category].push(asset)
      end
      items
    end

    def am_categorized_assets_group(assets, options = {})
      result = content_tag(:div, class: 'categorized_assets_group') do
        items = []
        categories_assets(assets).each do |asset_category_id, assets|
          items.push(
            content_tag(:h3) { AssetManager::AssetCategory.find(asset_category_id).title rescue t('.other') } +
            am_assets_group(assets, options)
          )
        end
        safe_join items, ''
      end
      raw(result)
    end

    def am_assets_group(assets, options = {})
      options.assert_valid_keys(:ico_size)
      content_tag(:div, class: 'assets_group') do
        items = []
        assets.each do |asset|
          items.push(am_render_file(asset, options))
        end
        safe_join items, ''
      end
    end
  end
end

app/helpers/asset_manager/links_helper.rb
module AssetManager
  module LinksHelper
    def show_resource_link(resource)
      link_to url_for(resource), title: t('show', default: 'Show') do
        content_tag(:i, class: 'icon-eye-open') { '' }
      end
    end

    def edit_resource_link(resource)
      link_to url_for(resource) + '/edit', title: t('edit', default: 'Edit') do
        content_tag(:i, class: 'icon-pencil') { '' }
      end
    end

    def delete_resource_link(resource)
      link_to url_for(resource), title: t('delete', default: 'Delete'), method: :delete, data: { confirm: t('.delete_confirmation', default: 'Are you sure?') } do
        content_tag(:i, class: 'icon-remove') { '' }
      end
    end
  end
end

app/views/asset_manager/assets/_asset.html.haml
- unless asset.nil?
  .resource.asset
    = "Id: #{asset.id}"

app/views/asset_manager/assets/_asset_draggable.html.haml
- unless asset.nil?
  .resource.asset.draggable{ data: { id: asset.id } }
    .thumbnail
      .caption
        %h5= asset.title
        .details
          = render partial: 'asset_manager/asset_instances/asset_instances', locals: { collection: asset.asset_instances }

app/views/asset_manager/assets/_asset_instance_fields.haml
.nested-fields
  .well.well-small
    = f.inputs do
      %div{ class: "#{AssetManager::AssetInstance.instance_contexts_with_all.length == 1 ? 'hide' : ''}" }
        = f.input :instance_context, as: :select, collection: AssetManager::AssetInstance.instance_contexts_with_all, input_html: { style: 'width: 60px' }, label: t('.instance_context')
      = f.input :file, as: :file
      - unless f.object.file.blank? || f.object.id.blank?
        .item= render partial: '/asset_manager/asset_instances/asset_instance', locals: { resource: f.object }
      - unless AssetManager::AssetInstance.instance_contexts_with_all.length == 1
        = link_to_remove_association '(x) ' + t('.remove_asset_instance'), f

app/views/asset_manager/assets/_assets.html.haml
- unless assets.empty?
  .resources.asset
    - assets.each do |asset|
      = render partial: '/admin/asset_manager/assets/asset', locals: {asset: asset}

app/views/asset_manager/assets/_assets_draggable.html.haml
- unless assets.empty?
  - assets.each do |asset|
    = render partial: 'asset_draggable', locals: { asset: asset }
  - pagination ||= false
  - if pagination
    .assets-navigation
      = paginate assets, remote: true

app/views/asset_manager/assets/_form.html.haml
= semantic_form_for @asset, multipart: true, builder: FormtasticBootstrap::FormBuilder, namespace: 'asset', class: 'form-horizontal' do |f|
  = render partial: 'asset_manager/partials/form_errors', locals: { errors: f.object.errors }
  = f.input :public, as: :hidden
  .form-horizontal
    = f.inputs t('.translations'), class: 'translations', data: { count: I18n.available_locales.count } do
      = render 'asset_manager/partials/locales_tabs'
      .tab-content
        = f.semantic_fields_for :translations, @asset.translations do |ft|
          = render 'translated_fields', f: ft
    - if AssetManager.with_categories || AssetManager.with_tags
      = f.inputs t('.general'), class: 'general' do
        - if AssetManager.with_categories
          = f.input :asset_category, collection: AssetManager::AssetCategory.sorted
        - if AssetManager.with_tags
          = f.input :tag_list
    = f.inputs 'File/s', class: 'general' do
      #asset_instances
        - association_name = "asset_#{@asset.public ? 'public' : 'private'}_instances".to_sym
        = f.semantic_fields_for association_name do |asset_instance|
          = render 'asset_instance_fields', f: asset_instance
        - unless AssetManager::AssetInstance.instance_contexts_with_all.length == 1
          .links= link_to_add_association '(+) ' +  t('.add_asset_instance'), f, association_name, partial: 'asset_instance_fields'
    = f.actions

:javascript
  $(document).ready(function() {
    $('form').submit(function() {
      submit = true;

      // Check instance context
      ics = new Array();
      $('#asset_instances .nested-fields:visible').each(function() {
        ic = $(this).find('select').val();
        if ($.inArray(ic, ics) == -1) {
          ics.push(ic);
        } else {
          submit = false;
          alert('Non è possibile avere più files dello stesso contesto (' + ic + ')');
          return false;
        }
      });

      // Check files
      numFiles = 0;
      $('#asset_instances .nested-fields:visible').each(function() {
        file = $(this).find('input[type=file]').val();
        item = $(this).find('.item');
        if (file || item) {
          numFiles++;
        }
      });
      if (! numFiles) {
        submit = false;
        alert('Non è possibile procedere senza aver selezionato un file');
        return false;
      }

      if (! submit) {
        return false;
      }
    });
  });

app/views/asset_manager/assets/_new_actions.html.haml
- if AssetManager.public_asset_type?
  = link_to(new_asset_path(public: true), class: 'btn') do
    %i.icon-plus-sign
    = (AssetManager.unique_asset_type? ? t('.new_asset') : t('.new_public_asset'))
- if AssetManager.private_asset_type?
  = link_to(new_asset_path(public: false), class: 'btn') do
    %i.icon-plus-sign
    = (AssetManager.unique_asset_type? ? t('.new_asset') : t('.new_private_asset'))

app/views/asset_manager/assets/_quick_upload.html.haml
#quick_upload
  = link_to 'javascript:void(0)', class: 'link-upload' do
    %i.icon-plus-sign
    %span= t('.quick_upload')
  .well.hide
    = form_for AssetManager::Asset.new, url: quick_upload_assets_path do |f|
      - asset_type = AssetManager.asset_types.first
      = f.hidden_field :public, value: (asset_type == :public ? true : false)
      = f.hidden_field :instance_context, name: "asset[asset_#{asset_type}_instances_attributes][0][instance_context]", value: AssetManager::AssetInstance.instance_context_all
      = f.hidden_field :locale, name: 'asset[translations_attributes][0][locale]', value: I18n.default_locale
      = f.hidden_field :title, name: 'asset[translations_attributes][0][title]', value: ''
      = f.file_field :file, name: "asset[asset_#{asset_type}_instances_attributes][0][file]", multiple: true
    %script#template-upload{ type: 'text/x-tmpl'}
      .upload
        = '{%=o.name%}'
        .progress.progress-striped.active
          .bar{ style: 'width: 0%'}

app/views/asset_manager/assets/_translated_fields.html.haml
%div{id: f.object.locale, class: "tab-pane#{f.object.locale.to_sym == I18n.default_locale.to_sym ? ' active' : ''}"}
  = f.input :locale, as: :hidden
  = f.input :title, required: true
  = f.input :description#, required: true

app/views/asset_manager/assets/index.html.haml
= content_for :page_title do
  = am_title t('.title_assets')
= content_for :page_actions do
  = render partial: 'new_actions'

= render partial: 'quick_upload'

.row-fluid
  .span10
    - if @assets.empty?
      = t('.no_results')
    - else
      %table.table.table-striped.table-bordered.table-hover.table-condensed
        %thead
          %tr
            %th= t('.id')
            %th= t('.asset_title')
            -#%th= t('.description')
            - if AssetManager.with_categories
              %th= t('.asset_category')
            - unless AssetManager.unique_asset_type?
              %th= t('.public')
            %th= t('.file_type')
            %th= t('.asset_instances')
            %th.actions= t('.actions')
        %tbody
          - @assets.each do |asset|
            %tr
              %td= asset.id
              %td= asset.title
              -#%td= asset.description
              - if AssetManager.with_categories
                %td= asset.asset_category.title rescue ''
              - unless AssetManager.unique_asset_type?
                %td= asset.public
              %td= asset.file_type
              %td= render partial: 'asset_manager/asset_instances/asset_instances', locals: { collection: asset.asset_instances, clippy: true }
              %td.actions
                %ul
                  %li= show_resource_link(asset)
                  %li= edit_resource_link(asset)
                  %li= delete_resource_link(asset)

      = render partial: 'asset_manager/partials/pagination_status', locals: { collection: @assets, total_records: @total_records }
      = paginate @assets, theme: 'bootstrap'
  .span2
    .well.filters
      .filters-title= t('labels.filters')
      = form_for @q, url: assets_path, html: { method: :get, style: 'margin-bottom: 0' } do |f|
        %div
          = f.label :translations_title_or_translations_description_cont, t('.title_or_description_contains')
          = f.text_field :translations_title_or_translations_description_cont
        - if AssetManager.with_categories
          %div
            = f.label :asset_category_id_eq, t('.asset_category_equal')
            = f.collection_select :asset_category_id_eq, AssetManager::AssetCategory.sorted, :id, :title, include_blank: true
        - unless AssetManager.unique_asset_type?
          %div
            = f.label :public_eq, t('.public_equal')
            = f.select :public_eq, [true, false], include_blank: true
        %div
          = f.label :file_type_eq, t('.file_type_equal')
          = f.select :file_type_eq, AssetManager::Asset.pluck(:file_type).uniq.compact, include_blank: true
        %div
          %button.btn{ type: 'submit', name: 'commit' }
            %i.icon-search
            = t('.search')
          = link_to t('.clear'), assets_path, class: 'btn btn-link'

app/views/asset_manager/assets/new.html.haml
= content_for :page_title do
  = am_title t('.title')

= render 'form'

app/views/asset_manager/assets/select.js.erb
$('#sortable1').html('<%= escape_javascript(render partial: 'assets_draggable', locals: { assets: @assets, pagination: true }) %>')

app/views/asset_manager/assets/show.html.haml
= content_for :page_title do
  = am_title @asset.title
= content_for :page_actions do
  = link_to(edit_asset_path(@asset), class: 'btn') do
    %i.icon-pencil
    = t('.edit')

%table.table.table-bordered.table-condensed.table-striped
  %thead
    %tr
      %th{ colspan: 2 }= t('.general')
  %tbody
    %tr
      %td= t('.id')
      %td= @asset.id
    %tr
      %td= t('.created_at')
      %td= @asset.created_at
    %tr
      %td= t('.updated_at')
      %td= @asset.updated_at

%table.table.table-bordered.table-condensed.table-striped
  %thead
    %tr
      %th{ colspan: 2 }= t('.details')
  %tbody
    %tr
      %td= t('.title')
      %td= @asset.translations.map{ |t| "[#{t.locale}] #{t.title}" }.join(', ')
    %tr
      %td= t('.description')
      %td= @asset.translations.map{ |t| "[#{t.locale}] #{t.description}" }.join(', ')
    - if AssetManager.with_categories
      %tr
        %td= t('.asset_category')
        %td= @asset.asset_category.title rescue ''
    - unless AssetManager.unique_asset_type?
      %tr
        %td= t('.public')
        %td= @asset.public
    - if AssetManager.with_tags
      %tr
        %td= t('.tags')
        %td= @asset.tag_list
    %tr
      %td= t('.file_type')
      %td= @asset.file_type
    %tr
      %td= t('.asset_instances')
      %td= render partial: 'asset_manager/asset_instances/asset_instances', locals: { collection: @asset.asset_instances }